[package]
name = "FAI"
version = "1.0.2"

[addresses]
StarcoinFramework = "0x1"
FaiAdmin = "0xFE125d419811297dfAB03c61EfEC0bC9"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="01c84198819310620f2417413c3c800df8292ae5"}

